let dadosJson = {
    perguntas:[
            '01- Amor a primeira vista é possível entre algumas pessoas.',
            '02- O sexo pré-marital é aceitável quando o casal gosta muito um do outro.',
            '03- Você saberá quando  o amor que sente é ou não verdadeiro.',
            '04- Quando o casal se ama de verdade não há brigas.',
            '05- É difícil notar a diferença entre o verdadeiro amor e a paixão.',
            '06- É normal alguém amar várias pessoas ao mesmo tempo.',
            '07- Quando você ama realmente, perde o interesse por outras coisas, pessoas e atividades.',
            '08- Quando você ama perdidamente alguém, percebe pelos seus sentimentos se é a pessoa certa.',
            '09- Assim que o casal descobre o verdadeiro amo, deve casar-se tão logo seja possível.',
            '10- Um jovem, antes de torna-se um adulto amadurecido, terá que se enamorar várias vezes, de várias pessoas diferentes.',
            '11- Amor é algo que você não pode estudar ou para o qual não pode prepara-se, visto ser uma resposta emocional.',
            '12- Quando você ama realmente vê só o que é bom na outra pessoa.',
            '13- A aprovação da familia e dos amigos não é de grande importância para seu relacionamento amoroso - isto diz respeito somente a você dois.',
            '14- Um período de afastamento faz com que um se afeiçoe mais ao outro.',
            '15- Quando você ama de verdade, não há, em seu relacionamento, a frequência presente de discussão, argumentações e mal entendimentos.',
            '16- Quando você ama, é capaz de  sobrepor todos os obstáculos sem levar em conta as diferenças entre os dois.',
            '17- Quando você está amando, gasta um bocado de tempo sonhando acordado.',
            '18- É melhor casar com a pessoa errada do que ficar solteiro.',
            '19- Quando você ama trabalha mais arduamente, produz mais, planeja melhor e age num nível mais elevado que nunca.',
            '20- Deus criou e escolheu uma pessoa para você. Através oração e da busca, você será levado ao encontro dessa pessoa.',
             
    ],
    respostas:[
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'V',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'F',
            'V',
            'F',
    ],
    dicas:[
        'Você possui uma boa compreensão do amor genuíno!',
        'Você não está mal, mas poderia precisar de alguma ajuda!',
        'Você está precisando definitivamente de ajuda para compreender o que significa o amor genuíno!'
    ]
};